<?php
// $Id: riffly.module,v 1.4 2009/02/19 19:54:49 btopro Exp $
//Riffly - View and Leave audio / video comments inline!
//@file
/**
 * hook_init
 * Add this onto each page
 */
function riffly_init() {
  // add external links to riffly javascript and styling.
  drupal_add_css(drupal_get_path('module', 'riffly') .'/riffly_style.css');
  drupal_add_js(drupal_get_path('module', 'riffly') .'/script.js');
  drupal_add_js(_riffly_build_js(),'inline');
}

/**
 * hook_menu
 * only thing available is the admin settings. 
 **/
function riffly_menu() {	  
    $items['admin/settings/riffly'] = array(
      'title'    => 'Riffly',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('riffly_settings'),
      'type'     => MENU_NORMAL_ITEM,
      'access arguments'   => array('administer site configuration'),
    );
  return $items;
}

/**
 * hook_perm
 * add video/audio comment
 * view video/audio comment
 **/
function riffly_perm() {
  return array('add video comment', 'add audio comment', 'view audio comment', 'view video comment');
}

/**
 * admin settings for riffly.
 * globally enable/disable riffly video and or audio comments
 **/
function riffly_settings() {
  $form = array();
  $form['riffly']['riffly_webcam_comments'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow Webcam Comments'),
    '#default_value' => variable_get('riffly_webcam_comments', TRUE),
    '#description' => t('Allow webcam comments to be left on your site'),
  );
  $form['riffly']['riffly_audio_comments'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow Audio Comments'),
    '#default_value' => variable_get('riffly_audio_comments', TRUE),
    '#description' => t('Allow audio comments to be left on your site'),
  );
  return system_settings_form($form);
}

/**
 * helper function generates the HTML to display the riffly comment players 
 * when these are embedded into the comments.
 **/
function riffly_video_display($comment_id, $riffly_id) {

  $riffly_comment_video = <<<OUTPUT
  <div id="riffly_video_player_%s">
  </div>
  <div id="riffly_video_player_%s_link">

  <table width="400" align="center">
  <tr>
    <td align="left" valign="middle" width="150">
      &nbsp;
    </td>
    <td align="left" valign="middle" width="130">
      <a href="javascript:void(0);" onclick="rifflyShowPlayer('riffly_video_player_%s', '%s', 'video');return false;" style="font-weight: bold;font-size: 18px;text-align: center;text-decoration: none;">Play Video<br>Comment &raquo;</a>
    </td>

    <td align="left" valign="top" width="120">
      <div class="video_thumbnail">
      <a href="javascript:void(0);" onclick="rifflyShowPlayer('riffly_video_player_%s', '%s', 'video');return false;" style="text-decoration: none;"><img src="http://free-video-comments-at.riffly.com/static/flv/%s.tiny.jpg" width="80" height="60" style="margin-top: 10px;margin-bottom: 0px;margin-left: 45px;border: 1px #000 solid;"><img src="http://free-video-comments-at.riffly.com/static/images/play_button.gif" alt="Play Video Comment" border="0" class="overlay_button_video"></a>
      </div>
    </td>
  </tr>
  </table>
  </div>
OUTPUT;

  return sprintf($riffly_comment_video, $comment_id, $comment_id, $comment_id, $riffly_id, $comment_id, $riffly_id, $riffly_id);
}

/**
 * helper function generates the HTML to display the riffly comment players 
 * when these are embedded into the comments.
 **/
function riffly_audio_display($comment_id, $riffly_id) {

  $riffly_comment_audio = <<<OUTPUT
  <div id="riffly_audio_player_%s">
  </div>
  <div id="riffly_audio_player_%s_link">

  <table width="400" align="center">
  <tr>
    <td align="left" valign="middle" width="150">
      &nbsp;
    </td>
    <td align="left" valign="middle" width="130">
      <a href="javascript:void(0);" onclick="rifflyShowPlayer('riffly_audio_player_%s', '%s', 'audio');return false;" style="font-weight: bold;font-size: 18px;text-align: center;text-decoration: none;">Play Audio Comment &raquo;</a>
    </td>
    <td align="left" valign="top" width="120">
      <div class="video_thumbnail">
      <a href="javascript:void(0);" onclick="rifflyShowPlayer('riffly_audio_player_%s', '%s', 'audio');return false;" style="text-decoration: none;"><img src="http://free-video-comments-at.riffly.com/static/images/audio_comment.gif" width="80" height="60" style="border: 1px #000 solid;margin-top: 10px;margin-bottom: 0;margin-left: 50px;text-decoration: none;"><img src="http://free-video-comments-at.riffly.com/static/images/play_button.gif" alt="Play Video Comment" border="0" class="overlay_button_audio"></a>
      </div>
    </td>
  </tr>
  </table>
  </div>
OUTPUT;
  
  return sprintf($riffly_comment_audio, $comment_id, $comment_id, $comment_id, $riffly_id, $comment_id, $riffly_id);
}

/**
 * function hook_comment
 **/
function riffly_comment(&$arg, $op) {

  switch($op) {
    case 'insert': //Get the riffly comments and insert into our db
      //do nothing embed comments in the comment text for now.
      break;

    case 'view':  //filter riffly comments and save..
      $comment = $arg->comment;

      $pattern = '/\[riffly_video\](.*)\[\/riffly_video\]/';

      if (user_access('view video comment')) {
	preg_match_all($pattern, $comment, $matches);

	foreach ($matches[1] as $riffly_id) {
	  $comment_id = $arg->cid;
	  $pattern = '/\[riffly_video\]' . $riffly_id . '\[\/riffly_video\]/';
	  $replacement = riffly_video_display($comment_id, $riffly_id);
	  $comment = preg_replace($pattern, $replacement, $comment);
	}
      }
      else {
	$comment = preg_replace($pattern, '', $comment);
      }

      $pattern = '/\[riffly_audio\](.*)\[\/riffly_audio\]/';
      if (user_access('view audio comment')) {
	preg_match_all($pattern, $comment, $matches);

	foreach ($matches[1] as $riffly_id) {
	  $comment_id = $arg->cid;
	  $pattern = '/\[riffly_audio\]' . $riffly_id . '\[\/riffly_audio\]/';
	  $replacement = riffly_audio_display($comment_id, $riffly_id);
	  $comment = preg_replace($pattern, $replacement, $comment);
	}
      }
      else {
	$comment = preg_replace($pattern, '', $comment);
      }

      $arg->comment = $comment;
      break;
  }

}

/**
 * Helper function to use permissions of Drupal with riffly by hiding js functions
 */
function _riffly_build_js() {
	$perms = '';
	$js = '';
	if ( user_access('add video comment') && 
		 user_access('add audio comment') && 
		 variable_get('riffly_webcam_comments', TRUE) && 
		 variable_get('riffly_audio_comments', TRUE) ) {
		$perms = 'both';
	}
	elseif (variable_get('riffly_webcam_comments', TRUE) && user_access('add video comment')) {
		$perms = 'video';
	}
	elseif (variable_get('riffly_audio_comments', TRUE) && user_access('add audio comment')) {
		$perms = 'audio';
	}
	else {
		$perms = 'none';
	}
	//print $perms;
	switch ($perms){
		case 'both': 
			$js = '<div id=\"riffly_button_window\" style=\"position: relative;width: 260px;z-index: 1500;font-weight: bold;font-size: 14px;\"><a style=\"font-weight: bold;font-size: 14px;\" href=\"javascript:void(0);\" onclick=\"rifflyShowRecorder('."'riffly_recorder_window', 'edit-comment', 'video'".');\"><img src=\"http://free-video-comments-at.riffly.com/static/images/api/blog/1/riffly-webcam.gif\" border=\"0\" width=\"16\" height=\"16\"> Add Webcam Comment</a><br><a style=\"font-weight: bold;font-size: 14px;\" href=\"javascript:void(0);\" onclick=\"rifflyShowRecorder('."'riffly_recorder_window', 'edit-comment', 'audio'".');\"><img src=\"http://free-video-comments-at.riffly.com/static/images/api/blog/1/riffly-mic.gif\" border=\"0\" width=\"16\" height=\"16\"> Add Audio-only Comment</a></div><div id=\"riffly_recorder_window\" style=\"display: none;position: relative;z-index: 2000;\">test</div>';
		break;
		case 'audio': 
			$js = '<div id=\"riffly_button_window\" style=\"position: relative;width: 260px;z-index: 1500;font-weight: bold;font-size: 14px;\"><a style=\"font-weight: bold;font-size: 14px;\" href=\"javascript:void(0);\" onclick=\"rifflyShowRecorder('."'riffly_recorder_window', 'edit-comment', 'audio'".');\"><img src=\"http://free-video-comments-at.riffly.com/static/images/api/blog/1/riffly-mic.gif\" border=\"0\" width=\"16\" height=\"16\"> Add Audio-only Comment</a></div><div id=\"riffly_recorder_window\" style=\"display: none;position: relative;z-index: 2000;\">test</div>';		
		break;
		case 'video': 
			$js = '<div id=\"riffly_button_window\" style=\"position: relative;width: 260px;z-index: 1500;font-weight: bold;font-size: 14px;\"><a style=\"font-weight: bold;font-size: 14px;\" href=\"javascript:void(0);\" onclick=\"rifflyShowRecorder('."'riffly_recorder_window', 'edit-comment', 'video'".');\"><img src=\"http://free-video-comments-at.riffly.com/static/images/api/blog/1/riffly-webcam.gif\" border=\"0\" width=\"16\" height=\"16\"> Add Webcam Comment</a></div><div id=\"riffly_recorder_window\" style=\"display: none;position: relative;z-index: 2000;\">test</div>';
		break;
	}
	
	return 'rifflyQuery(document).ready(function() {

	if (! rifflyQuery("#riffly_recorder_window").length) {
		if (rifflyQuery("input[name=action]").attr("value") != "editedcomment") { /* not admin edit comment mode */
			rifflyQuery("textarea[name=comment]").before("'. $js .'");
		}
	}
});';
}