<?php

/**
 * @file Disable password strength checker.
 *
 * Code originally taken from from
 * http://www.drupalcoder.com/story/409-disabling-password-check-in-drupal-6
 *
 */

/**
 * Implementation of hook_init().
 */
function disablepwstrength_init() {
  // If the user is currently on a user/* page or the admin/user/user page, insert the JS.
    drupal_add_js(drupal_get_path('module', 'disablepwstrength') .'/disablepwstrength.js', 'module', 'footer');
}

